# Set up the pod configuration for deploying App-B to cluster
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: pod-b
spec:
  containers:
    - name: nodejs
      image: siravichmek/kubernetes:application-b
      ports:
        - containerPort: 8085

    - name: mysql
      image: siravichmek/kubernetes:application-b-mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: app-b
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

    - name: phpmyadmin
      image: siravichmek/kubernetes:application-b-phpmyadmin
      env:
        - name: PMA_HOST
          value: mysql
        - name: PMA_USER
          value: root
        - name: PMA_PASSWORD
          value: root
      ports:
        - containerPort: 80

  volumes:
    - name: mysql-data
      emptyDir: {}
