apiVersion: v1
kind: Service
metadata:
  name: pod-b
spec:
  type: NodePort
  selector:
    app: pod-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
      nodePort: 30014 # Specify the desired NodePort here
