apiVersion: v1
kind: Service
metadata:
  name: randomtext-service
spec:
  type: NodePort
  selector:
    app: randomtext-service  # Corrected selector to match the label of pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001  # Correct targetPort to match the port your application listens on
    nodePort: 30000
