version: '3'

services:
  nodejs:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-a
    volumes:
      - ./mysql-data:/var/lib/mysql
    
    networks:
      backend:
        ipv4_address: 172.20.0.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "9097:80"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
