apiVersion: v1
kind: Service
metadata:
  name: grant-role-service
spec:
  type: NodePort
  selector:
    app: grant-role-service  # Corrected selector to match the label of pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002  # Correct targetPort to match the port your application listens on
    nodePort: 30070
