apiVersion: v1
kind: Service
metadata:
  name: gentoken-service2
spec:
  type: NodePort
  selector:
    app: gentoken-service2  # Corrected selector to match the label of pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3008  # Correct targetPort to match the port your application listens on
    nodePort: 30035
